# Generated by Django 2.1.3 on 2019-03-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lane', '0002_image_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(upload_to='media/'),
        ),
    ]
