# Generated by Django 2.1.3 on 2019-03-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lane', '0003_auto_20190312_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(upload_to='document/'),
        ),
    ]
